agregar 1 caja mas
lpagency/patagonia2 pull request #5
Opened 2018-07-26 17:24 UTC by anilentp

2018-07-26 17:33 UTC, blur50 requested changes

2018-07-26 17:33 UTC, blur50 commented on templates/page/videos.html
> +                <div class="box_img" style="position: relative;">
La etiqueta "style" en este div y en otros elementos que tengan "style", ¿no podrían ocupar una alguna clase de css en vez de "style" directamente.?

2018-07-26 17:35 UTC, anilentp commented on templates/page/videos.html
> +                <div class="box_img" style="position: relative;">
@blur50 en verdad solo copie y pegue el tema, dejame ver como funciona con una clase css, porque es un sitio antiguo, y desordenado por ende, puede que ese atributo no lo tome

2018-07-26 17:36 UTC, blur50 commented on templates/page/videos.html
> +                <div class="box_img" style="position: relative;">
dale, espero a ver como te va, si no, lo apruebo directamente

2018-07-27 19:37 UTC, blur50 approved these changes

2018-08-06 19:14 UTC, merged